### ISSUE TITLE
Fix Package.Swift for iOS

### ISSUE THREAD

**Issue by waahm7** [awslabs/aws-crt-swift#159]
### Describe the bug

Currently, there are checks like https://github.com/awslabs/aws-crt-swift/blob/main/Package.swift#L117 which do not take care of what should happen for iOS. We should add explicit checks for iOS after researching.

**Comment by epau** [comment]
As part of this work, we must refactor our handling of platform and architecture specific dependencies. Currently, we use conditionals to specify specific files to use for a particular platform or architecture. Because applications may be cross compiled, this can result in an incorrect configuration. 

The package description provides a way to customize dependencies by platform https://github.com/apple/swift-evolution/blob/main/proposals/0273-swiftpm-conditional-target-dependencies.md

We must investigate if this also supports architecture based conditions and if not we must investigate a different way to handle customizing dependencies based on the target platform's architecture.

**Comment by waahm7** [comment]
As part of this work, we will also look at #163.
